# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dateianhang',
            new_name='Attachment'
        )
    ]
